version: '3.9'
services:
  capitalisk-core:
    container_name: capitalisk-core
    build: .
    restart: always
    ports:
      - '8001:8001'
    links:
      - postgres

  postgres:
    image: 'postgres:13'
    container_name: capitalisk-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ldpos
      POSTGRES_USER: ldpos
      POSTGRES_DB: capitalisk_main
