version: "3.9"
services:
  capitalisk-core:
    build: .
    restart: always
    ports:
      - "7010:7010"
      - "7001:7001"

  postgres:
    image: "posgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
