version: "3.9"
services:
  capitalisk-core:
    build: .
    restart: always
    ports:
      - "8001:8001"

  postgres:
    image: "postgres:13-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: ldpos
      POSTGRES_USER: ldpos
      POSTGRES_DB: capitalisk_main
    ports:
      - "5432:5432"
